[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
]
runner = "elf2uf2-rs --deploy --serial --verbose"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
